server:
  port: 9001

spring:
  application:
    name: catalog-service
  config:
    import: "optional:configserver:"
#  cloud:
#    config:
#      uri: http://localhost:8888
#      request-connect-timeout: 5000
#      request-read-timeout: 5000
#      fail-fast: true
#      retry:
#        max-attempts: 6
#        initial-interval: 1000
#        max-interval: 2000
#        multiplier: 1.1
  datasource:
    username: myusername
    password: mypass
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  flyway:
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: create
#  sql:
#    init:
#      mode: always